apply plugin: 'com.android.application'
apply plugin: 'com.diffplug.spotless'

android {
    namespace "br.net.du.customwebapp"
    compileSdk 36

    defaultConfig {
        applicationId "br.net.du.arhaticyogajournal"
        minSdkVersion 14
        targetSdkVersion 36
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
        }
    }

    testOptions {
        unitTests {
            all {
                useJUnitPlatform()
            }
        }
    }
}

dependencies {
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'androidx.appcompat:appcompat:1.0.0'
    implementation 'com.github.clans:fab:1.6.4'

    // JUnit 5
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.2'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.2'

    // Mockito
    testImplementation 'org.mockito:mockito-core:4.6.1'
    testImplementation "org.objenesis:objenesis:3.3"
}

configurations.implementation {
    spotless {
        java {
            // Ref.: https://github.com/diffplug/spotless/issues/240#issuecomment-385206606
            custom 'noWildcardImports', {
                if (it.contains('*;\n')) {
                    throw new Error('No wildcard imports allowed')
                }
            }
            bumpThisNumberIfACustomStepChanges(1)

            googleJavaFormat().aosp()
            target '**/*.java'
        }
    }
    preBuild.dependsOn(spotlessApply)
}
